<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "BLUDIT",
    "slogan": "Bem-vindo ao Bludit",
    "description": "Parab\u00e9ns! Voc\u00ea instalou o Bludit com sucesso.",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "pt_BR",
    "locale": "pt_BR",
    "timezone": "America\/Fortaleza",
    "theme": "nimbuss",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "https:\/\/aqua-hippopotamus-874519.hostingersite.com\/blog\/",
    "emailFrom": "no-reply@aqua-hippopotamus-874519.hostingersite.com",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false
}